/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lead = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SiteConfig = IDL.Record({ 'bookingUrl' : IDL.Text });
export const Init = IDL.Record({
  'admin' : IDL.Principal,
  'bookingUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getLeadsSortedByEmail' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getSiteConfig' : IDL.Func([], [SiteConfig], ['query']),
  'init' : IDL.Func([Init], [], []),
  'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateBookingUrl' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lead = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SiteConfig = IDL.Record({ 'bookingUrl' : IDL.Text });
  const Init = IDL.Record({ 'admin' : IDL.Principal, 'bookingUrl' : IDL.Text });
  
  return IDL.Service({
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getLeadsSortedByEmail' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getSiteConfig' : IDL.Func([], [SiteConfig], ['query']),
    'init' : IDL.Func([Init], [], []),
    'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateBookingUrl' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };